### ISSUE TITLE
Inconsistent variable names on instructions with multiple return values

### ISSUE THREAD

**Issue by JeanJPNM** [weisrc/mlogjs#20]
Usually assigned variables have their positions in the source file as names. However, that is not the case for variables that are outputted by commands with multiple return values like `unitLocate` and `unitControl` (this one in a specific function overload).

## Demonstration

Passing the following input to the compiler results in the following output:

```js
const [found, x, y, building] = unitLocate("building", "core", true);

print(found, x, y, building);
```

```
ulocate building core 1 @copper t1 t2 t0 t3
print t0
print t1
print t2
print t3
end
```

While the expected output is:

```
ulocate building core 1 @copper 1:14 1:17 1:7 1:20
print 1:7
print 1:14
print 1:17
print 1:20
end
```

I'm sure this has to do with how the macros for those instructions return `ObjectValue`s. 
One possible solution would be to add a sort "hook" that gets called when an `IValue` gets put into a scope with a name. That way certain types of values can rename their internal name to fit that of the scope variable holding them.

**Comment by weisrc** [comment]
I think it can be fixed in the handler VariableDeclaration ArrayPattern. Temp value extends Store value, thus we can add a name to it.

**Comment by weisrc** [comment]
Should I fix it? Or you will include it along with #19 ?

**Comment by JeanJPNM** [comment]
I will include it with #19

**Comment by JeanJPNM** [comment]
Better keep it open until it's actually fixed.
